SUMMARY = "Project Jupyter exists to develop open-source software, open-standards, and services for interactive computing across dozens of programming languages"
HOMEPAGE = "http://jupyter.org/"
LICENSE = "BSD"

LIC_FILES_CHKSUM = "file://LICENSE;md5=e5d3a9b8d105ce01fe369f89f3428b43"
SRC_URI[md5sum] = "c6030444c7eb6c05a4d7b1768c72aed7"
SRC_URI[sha256sum] = "d9dc4b3318f310e34c82951ea5d6683f67bed7def4b259fafbfe4f1beb1d8e5f"

CLEANBROKEN = "1"

PYPI_PACKAGE = "jupyter"
