SUMMARY = "IPython: Productive Interactive Computing"
DESCRIPTION = "IPython provides a rich toolkit to help you make the most out of using Python interactively."
HOMEPAGE = "https://ipython.org"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=96c7b03c4a9d8babd9ec57b1f0613d78"

SRC_URI[md5sum] = "601ef967631e3fa9d3ef43bc2f557249"
SRC_URI[sha256sum] = "9fed506c3772c875a3048bc134a25e6f5e997b1569b2636f6a5d891f34cbfd46"

CLEANBROKEN = "1"

PYPI_PACKAGE = "ipython"
