SUMMARY = "A fast implementation of the Cassowary constraint solver"
HOMEPAGE = "https://github.com/nucleic/kiwi"
LICENSE="BSD"
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=10c003483ba6ff6c1016623a319ed24f"
SRC_URI[md5sum] = "e2a1718b837e2cd001f7c06934616fcd"
SRC_URI[sha256sum] = "ce3be5d520b4d2c3e5eeb4cd2ef62b9b9ab8ac6b6fedbaa0e39cdb6f50644278"

CLEANBROKEN = "1"

PYPI_PACKAGE = "kiwisolver"
BBCLASSEXTEND = "native nativesdk"
