SUMMARY = "Manipulate audio with an simple and easy high level interface"
DESCRIPTION = "Manipulate audio with an simple and easy high level interface.\
See the README file for details, usage info, and a list of gotchas."
HOMEPAGE = "http://pydub.com"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://PKG_INFO;md5=403d8fd5340a201f4bcedf0e27efcf73"

SRC_URI[md5sum] = "71828816184107da705364e5391a5893"
SRC_URI[sha256sum] = "20beff39e9959a3b2cb4392802aecb9b2417837fff635d2b00b5ef5f5326d313"

CLEANBROKEN = "1"

PYPI_PACKAGE = "pydub"
