SUMMARY = "Python audio data toolkit (ID3 and MP3)"
HOMEPAGE = "http://eyed3.nicfit.net/"
DESCRIPTION = "eyeD3_ is a Python tool for working with audio files, specifically MP3 files \
containing ID3_ metadata (i.e. song info). \
It provides a command-line tool (``eyeD3``) and a Python library \
(``import eyed3``) that can be used to write your own applications or \
plugins that are callable from the command-line tool."
LICENSE = "GNU GPL v3.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=8006d9c814277c1bfc4ca22af94b59ee"

SRC_URI[md5sum] = "2f08a4bb8ed78218360c2f3e74a68a50"
SRC_URI[sha256sum] = "ef924eb2e8fffd7c7e3bd4c94dafad4a3b9047fe2dcb76d5dd7d9c37a1f1f8bb"

CLEANBROKEN = "1"

PYPI_PACKAGE = "eyeD3"
