SUMMARY = "Computer algebra system (CAS) in Python"
HOMEPAGE = "http://sympy.org"
DESCRIPTION = "SymPy is a Python library for symbolic mathematics. It aims to become a \
full-featured computer algebra system (CAS) while keeping the code as simple \
as possible in order to be comprehensible and easily extensible.  SymPy is \
written entirely in Python. It depends on mpmath, and other external libraries \
may be optionally for things like plotting support."
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=4fc6959419037a1f364a7615166e79af"

SRC_URI[md5sum] = "11e18423f52e248108a3bd4307185bc1"
SRC_URI[sha256sum] = "e1319b556207a3758a0efebae14e5e52c648fc1db8975953b05fff12b6871b54"

CLEANBROKEN = "1"

PYPI_PACKAGE = "sympy"
